openapi: 3.0.0
info:
  title: API de Zonas de Trabajo y Clientes TATSoft
  description: API para la gestión de áreas de trabajo, clientes y asignación de zonas a usuarios
  version: 1.0.0

servers:
  - url: http://localhost:10101
    description: Servidor local
  - url: https://backendareasandclients-apgba5dxbrbwb2ex.eastus2-01.azurewebsites.net
    description: Servidor de producción

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Area:
      type: object
      properties:
        nombre_zona_trabajo:
          type: string
          minLength: 1
          maxLength: 45
          description: Nombre del área de trabajo
        descripcion:
          type: string
          maxLength: 255
          description: Descripción del área de trabajo
          
    Client:
      type: object
      properties:
        cedula:
          type: string
          minLength: 6
          maxLength: 15
          description: Número de cédula del cliente
        nombre_completo_cliente:
          type: string
          minLength: 6
          maxLength: 200
          description: Nombre completo del cliente
        direccion:
          type: string
          minLength: 5
          maxLength: 255
          description: Dirección del cliente
        telefono:
          type: string
          minLength: 8
          maxLength: 15
          description: Número de teléfono del cliente
        rut_nit:
          type: string
          maxLength: 30
          description: RUT/NIT del cliente
        razon_social:
          type: string
          maxLength: 100
          description: Razón social del cliente
        estado:
          type: string
          enum: [Activo, Inactivo]
          description: Estado del cliente
        id_zona_de_trabajo:
          type: integer
          description: ID del área de trabajo asignada
    
    Error:
      type: object
      properties:
        error:
          type: string
          description: Mensaje de error
        details:
          type: string
          description: Detalles adicionales del error

paths:
  /register-area:
    post:
      security:
        - bearerAuth: []
      tags:
        - Áreas
      summary: Registrar nueva área de trabajo
      description: Crear una nueva área de trabajo en el sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Area'
      responses:
        '201':
          description: Área registrada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Zona registrada con éxito"
        '422':
          description: Error de validación
        '500':
          description: Error interno del servidor
          
  /get-areas:
    get:
      security:
        - bearerAuth: []
      tags:
        - Áreas
      summary: Obtener todas las áreas
      description: Retorna la lista de todas las áreas de trabajo
      responses:
        '200':
          description: Lista de áreas obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '500':
          description: Error interno del servidor

  /get-area/{id_zona_de_trabajo}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Áreas
      summary: Obtener un área específica
      description: Retorna un área de trabajo por su ID
      parameters:
        - name: id_zona_de_trabajo
          in: path
          required: true
          description: ID del área a buscar
          schema:
            type: integer
      responses:
        '200':
          description: Área encontrada exitosamente
        '404':
          description: Área no encontrada
        '500':
          description: Error interno del servidor
          
  /delete-area/{id_zona_de_trabajo}:
    delete:
      security:
        - bearerAuth: []
      tags:
        - Áreas
      summary: Eliminar un área
      description: Elimina un área de trabajo por su ID
      parameters:
        - name: id_zona_de_trabajo
          in: path
          required: true
          description: ID del área a eliminar
          schema:
            type: integer
      responses:
        '200':
          description: Área eliminada exitosamente
        '404':
          description: Área no encontrada
        '409':
          description: No se puede eliminar el área debido a referencias existentes
        '500':
          description: Error interno del servidor

  /update-area/{id_zona_de_trabajo}:
    put:
      security:
        - bearerAuth: []
      tags:
        - Áreas
      summary: Actualizar un área
      description: Actualiza la información de un área existente
      parameters:
        - name: id_zona_de_trabajo
          in: path
          required: true
          description: ID del área a actualizar
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Area'
      responses:
        '200':
          description: Área actualizada exitosamente
        '404':
          description: Área no encontrada
        '500':
          description: Error interno del servidor

  /register-client:
    post:
      security:
        - bearerAuth: []
      tags:
        - Clientes
      summary: Registrar nuevo cliente
      description: Crear un nuevo cliente en el sistema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '201':
          description: Cliente registrado exitosamente
        '422':
          description: Error de validación
        '500':
          description: Error interno del servidor

  /get-clients:
    get:
      security:
        - bearerAuth: []
      tags:
        - Clientes
      summary: Obtener todos los clientes
      description: Retorna la lista de todos los clientes
      responses:
        '200':
          description: Lista de clientes obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
        '500':
          description: Error interno del servidor

  /get-client/{id_cliente}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Clientes
      summary: Obtener un cliente específico
      description: Retorna un cliente por su ID
      parameters:
        - name: id_cliente
          in: path
          required: true
          description: ID del cliente a buscar
          schema:
            type: integer
      responses:
        '200':
          description: Cliente encontrado exitosamente
        '404':
          description: Cliente no encontrado
        '500':
          description: Error interno del servidor

  /delete-client/{id_cliente}:
    delete:
      security:
        - bearerAuth: []
      tags:
        - Clientes
      summary: Eliminar un cliente
      description: Elimina un cliente por su ID
      parameters:
        - name: id_cliente
          in: path
          required: true
          description: ID del cliente a eliminar
          schema:
            type: integer
      responses:
        '200':
          description: Cliente eliminado exitosamente
        '404':
          description: Cliente no encontrado
        '409':
          description: No se puede eliminar el cliente debido a referencias existentes
        '500':
          description: Error interno del servidor

  /update-client/{id_cliente}:
    put:
      security:
        - bearerAuth: []
      tags:
        - Clientes
      summary: Actualizar un cliente
      description: Actualiza la información de un cliente existente
      parameters:
        - name: id_cliente
          in: path
          required: true
          description: ID del cliente a actualizar
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Cliente actualizado exitosamente
        '404':
          description: Cliente no encontrado
        '500':
          description: Error interno del servidor

  /request-create-cliente:
    post:
      tags:
        - Solicitudes de Creación
      summary: Solicitud de creación de un nuevo cliente
      description: Permite a un colaborador enviar una solicitud para crear un nuevo cliente. La solicitud quedará pendiente de aprobación.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - cedula
                - nombre_completo_cliente
                - direccion
                - telefono
              properties:
                cedula:
                  type: string
                  minLength: 6
                  maxLength: 15
                  description: Número de identificación del cliente (cédula). Debe contener solo números.
                  example: "1234567890"
                nombre_completo_cliente:
                  type: string
                  minLength: 6
                  maxLength: 200
                  description: Nombre completo del cliente.
                  example: "Juan Pérez González"
                direccion:
                  type: string
                  minLength: 5
                  maxLength: 255
                  description: Dirección física del cliente.
                  example: "Calle Principal #123, Ciudad"
                telefono:
                  type: string
                  minLength: 8
                  maxLength: 15
                  description: Número de teléfono del cliente, solo dígitos.
                  example: "3001234567"
                rut_nit:
                  type: string
                  maxLength: 30
                  description: Número de identificación tributaria del cliente (opcional).
                  example: "900123456-7"
                razon_social:
                  type: string
                  maxLength: 100
                  description: Razón social para clientes empresariales (opcional).
                  example: "Empresa XYZ S.A.S."
                id_zona_de_trabajo:
                  type: integer
                  format: int32
                  minimum: 1
                  description: ID de la zona de trabajo a la que pertenece el cliente (opcional).
                  example: 5
      responses:
        '201':
          description: Cliente registrado con éxito (pendiente de aprobación)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "Cliente registrado con éxito"
        '401':
          description: No autorizado - Token no proporcionado o inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "token inválido o expirado"
        '403':
          description: Prohibido - El usuario no tiene permisos para realizar esta acción
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "No tienes permisos para realizar esta acción"
        '422':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        msg:
                          type: string
                        path:
                          type: string
                        location:
                          type: string
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      errorInfo:
                        type: string
                        example: "Duplicate entry '1234567890' for key 'cedula'"
                  - type: object
                    properties:
                      error:
                        type: string
                        example: "Internal Server Error"
                      details:
                        type: string

  /get-Pending-Request:
    get:
      security:
        - bearerAuth: []
      tags:
        - Solicitudes de Creación
      summary: Obtener solicitudes pendientes
      description: Retorna la lista de solicitudes de creación de clientes pendientes
      responses:
        '200':
          description: Lista de solicitudes obtenida exitosamente
        '404':
          description: No hay solicitudes pendientes
        '500':
          description: Error interno del servidor

  /accept-Reject-Request/{id_client}:
    put:
      security:
        - bearerAuth: []
      tags:
        - Solicitudes de Creación
      summary: Aceptar o rechazar solicitud
      description: Procesar una solicitud de creación de cliente
      parameters:
        - name: id_client
          in: path
          required: true
          description: ID del cliente de la solicitud
          schema:
            type: integer
      responses:
        '200':
          description: Solicitud procesada exitosamente
        '404':
          description: Solicitud no encontrada
        '500':
          description: Error interno del servidor

  /post-AreaUser/{id_usuario}:
    post:
      security:
        - bearerAuth: []
      tags:
        - Asignación de Áreas
      summary: Asignar áreas a usuario
      description: Asignar una o más áreas de trabajo a un usuario
      parameters:
        - name: id_usuario
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                zonas:
                  type: array
                  items:
                    type: integer
                  description: Lista de IDs de áreas a asignar
      responses:
        '200':
          description: Áreas asignadas exitosamente
        '400':
          description: Datos de entrada inválidos
        '500':
          description: Error interno del servidor

  /get-AreaUser/{id_usuario}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Asignación de Áreas
      summary: Obtener áreas de usuario
      description: Obtener las áreas asignadas a un usuario
      parameters:
        - name: id_usuario
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Áreas obtenidas exitosamente
        '404':
          description: Usuario no encontrado o sin áreas asignadas
        '500':
          description: Error interno del servidor

  /getClientsAreaUser/{id_usuario}/{id_zona}:
    get:
      security:
        - bearerAuth: []
      tags:
        - Asignación de Áreas
      summary: Obtener clientes de área asignada
      description: Obtener los clientes de un área asignada a un usuario
      parameters:
        - name: id_usuario
          in: path
          required: true
          description: ID del usuario
          schema:
            type: integer
        - name: id_zona
          in: path
          required: true
          description: ID del área
          schema:
            type: integer
      responses:
        '200':
          description: Clientes obtenidos exitosamente
        '404':
          description: No se encontraron clientes
        '500':
          description: Error interno del servidor